# Generated by Django 5.0.1 on 2024-08-11 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChouseCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chouse_Centre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chouse_centre',
            },
        ),
        migrations.CreateModel(
            name='chousejender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chouse_jender', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Other', 'Other')], max_length=10)),
            ],
            options={
                'db_table': 'chousejender',
            },
        ),
        migrations.CreateModel(
            name='ModelsChouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_names', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'models_chouse',
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=100)),
                ('Customer_fullname', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now=True)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=1000)),
                ('Address', models.CharField(default='Address', max_length=100)),
                ('Chouse_jender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.chousejender')),
                ('Model_centers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.chousecentre')),
                ('Models_chouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.modelschouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_drive',
            },
        ),
    ]
