# Generated by Django 5.1 on 2024-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_testdrive_user_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chousejender',
            name='Chouse_jender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
