# Generated by Django 5.0.1 on 2024-07-28 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=100)),
                ('Customer_fullname', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now=True)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=1000)),
                ('Address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
