# Generated by Django 5.0.1 on 2024-08-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_car_model_category_alter_service_address_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='model_price',
            field=models.IntegerField(),
        ),
    ]
