# Generated by Django 5.0.1 on 2024-08-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_car_model_model_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car_model',
            table='carmodel',
        ),
    ]
