# Generated by Django 5.0.1 on 2024-08-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_car_model_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_model',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='model',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Car_Model',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
