# Generated by Django 5.0.1 on 2024-08-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_category_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
