# Generated by Django 5.0.1 on 2024-08-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_alter_product_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='CarModel',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='product_name',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='product_price',
            new_name='model_price',
        ),
    ]
