# Generated by Django 5.0.1 on 2024-08-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_rename_product_carmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
