# Generated by Django 5.0.1 on 2024-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0009_carmodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'empimg',
            },
        ),
    ]
