# Generated by Django 5.0.1 on 2024-08-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0010_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmwModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='image')),
                ('model_name', models.CharField(max_length=50)),
                ('model_price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.category')),
            ],
            options={
                'db_table': 'bmwcar',
            },
        ),
        migrations.CreateModel(
            name='lamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='image')),
                ('model_name', models.CharField(max_length=50)),
                ('model_price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.category')),
            ],
            options={
                'db_table': 'lamcar',
            },
        ),
        migrations.CreateModel(
            name='MerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='image')),
                ('model_name', models.CharField(max_length=50)),
                ('model_price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.category')),
            ],
            options={
                'db_table': 'Mercar',
            },
        ),
        migrations.CreateModel(
            name='PorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='image')),
                ('model_name', models.CharField(max_length=50)),
                ('model_price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.category')),
            ],
            options={
                'db_table': 'Porcar',
            },
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='IMG',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
