# Generated by Django 5.0.1 on 2024-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0011_bmwmodel_lammodel_mermodel_pormodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
