# Generated by Django 5.0.1 on 2024-08-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0013_bookcars'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcars',
            name='img',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
