# Generated by Django 5.1 on 2024-08-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0014_bookcars_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookcars',
            table='booklist',
        ),
    ]
