# Generated by Django 5.1 on 2024-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0015_alter_bookcars_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('Payment_id', models.CharField(max_length=100)),
                ('Paid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PayMent_list',
            },
        ),
    ]
