# Generated by Django 5.1 on 2024-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0016_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_id',
            new_name='payment_id',
        ),
        migrations.AddField(
            model_name='bookcars',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
