# Generated by Django 5.1 on 2024-08-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0017_rename_amount_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcars',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.payment'),
        ),
    ]
