# Generated by Django 5.1 on 2024-08-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0018_bookcars_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcars',
            name='paid',
        ),
    ]
